// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MultipleTablesData.DatabaseContext;

#nullable disable

namespace MultipleTablesData.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20241009134246_first1")]
    partial class first1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MultipleTablesData.Department", b =>
                {
                    b.Property<int>("DepartmentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DepartmentId"));

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DepartmentId");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            DepartmentId = 1,
                            DepartmentName = "IT"
                        },
                        new
                        {
                            DepartmentId = 2,
                            DepartmentName = "HR"
                        },
                        new
                        {
                            DepartmentId = 3,
                            DepartmentName = "Accounts"
                        },
                        new
                        {
                            DepartmentId = 4,
                            DepartmentName = "Payroll"
                        },
                        new
                        {
                            DepartmentId = 5,
                            DepartmentName = "Admin"
                        });
                });

            modelBuilder.Entity("MultipleTablesData.Employee", b =>
                {
                    b.Property<int>("EmployeeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("EmployeeId"));

                    b.Property<DateTime>("DateOfBirth")
                        .HasColumnType("datetime2");

                    b.Property<int>("DepartmentId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Gender")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.Property<string>("PhotoPath")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("EmployeeId");

                    b.HasIndex("DepartmentId");

                    b.HasIndex("LocationId");

                    b.ToTable("Employees");

                    b.HasData(
                        new
                        {
                            EmployeeId = 1,
                            DateOfBirth = new DateTime(1990, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "john.Doe@email.com",
                            FirstName = "John",
                            Gender = 0,
                            LastName = "Doe",
                            LocationId = 1,
                            PhotoPath = "Images/john.png"
                        },
                        new
                        {
                            EmployeeId = 2,
                            DateOfBirth = new DateTime(1980, 12, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "Frank.Hughes@email.com",
                            FirstName = "Frank",
                            Gender = 0,
                            LastName = "Hughes",
                            LocationId = 2,
                            PhotoPath = "Images/frank.png"
                        },
                        new
                        {
                            EmployeeId = 3,
                            DateOfBirth = new DateTime(1994, 1, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 3,
                            Email = "Rose.Marfo@email.com",
                            FirstName = "Rose",
                            Gender = 1,
                            LastName = "Marfo",
                            LocationId = 3,
                            PhotoPath = "Images/rose.png"
                        },
                        new
                        {
                            EmployeeId = 4,
                            DateOfBirth = new DateTime(2000, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 4,
                            Email = "Sandra.Armah@email.com",
                            FirstName = "Sandra",
                            Gender = 1,
                            LastName = "Armah",
                            LocationId = 4,
                            PhotoPath = "Images/sandra.png"
                        },
                        new
                        {
                            EmployeeId = 5,
                            DateOfBirth = new DateTime(1987, 5, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 1,
                            Email = "Dennis.Marfo@email.com",
                            FirstName = "Dennis",
                            Gender = 0,
                            LastName = "Marfo",
                            LocationId = 5,
                            PhotoPath = "Images/dennis.png"
                        },
                        new
                        {
                            EmployeeId = 6,
                            DateOfBirth = new DateTime(2001, 5, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentId = 2,
                            Email = "Mabel.Abekah@email.com",
                            FirstName = "Mabel",
                            Gender = 1,
                            LastName = "Abekah",
                            LocationId = 2,
                            PhotoPath = "Images/mabel.png"
                        });
                });

            modelBuilder.Entity("MultipleTablesData.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("LocationName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            LocationName = "Bombay"
                        },
                        new
                        {
                            LocationId = 2,
                            LocationName = "Delhi"
                        },
                        new
                        {
                            LocationId = 3,
                            LocationName = "HYD"
                        },
                        new
                        {
                            LocationId = 4,
                            LocationName = "Chennai"
                        },
                        new
                        {
                            LocationId = 5,
                            LocationName = "Bengaluru"
                        });
                });

            modelBuilder.Entity("MultipleTablesData.Employee", b =>
                {
                    b.HasOne("MultipleTablesData.Department", "Department")
                        .WithMany()
                        .HasForeignKey("DepartmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MultipleTablesData.Location", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Department");

                    b.Navigation("Location");
                });
#pragma warning restore 612, 618
        }
    }
}
